on:
  push:
    tags:
      - "v*.*.*"

name: Build and Release

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org

      - name: Verify versions
        run: node --version && npm --version && node -p process.versions.v8

      - name: Cache build artifacts
        id: cache-node
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            .chappe
            node_modules
          key: build-${{ runner.os }}-node-any

      - name: Install dependencies
        run: npm install

      - name: Release package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
